apiVersion: apps/v1
kind: Deployment
metadata:
  name: yunpan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunpan
  template:
    metadata:
      labels:
        app: yunpan
    spec:
      containers:
      - name: yunpan

---

apiVersion: v1
kind: Service
metadata:
  name: yunpan
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "yunpan"
    port: 8080
  selector:
    app: yunpan
